# Generated by Django 5.2.13 on 2026-05-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='post', max_length=20)),
                ('caption_text', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brandprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
