# Generated by Django 5.2.13 on 2026-05-25 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(choices=[('dentista', 'Dentista'), ('estetica', 'Estética/Harmonização'), ('hamburgueria', 'Restaurantes/Hamburguerias'), ('personal', 'Personal Trainer'), ('nutricionista', 'Nutricionista'), ('imobiliaria', 'Imobiliária'), ('advogado', 'Advogado'), ('barbearia', 'Barbearia'), ('loja_feminina', 'Loja Feminina'), ('influenciador', 'Influenciador Local')], max_length=50, verbose_name='Nicho de Atuação')),
                ('brand_name', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('tone_of_voice', models.CharField(help_text='Ex: Divertido e informal, Sério e focado em vendas, etc.', max_length=100, verbose_name='Tom de Voz')),
                ('primary_color', models.CharField(help_text='Código Hex. Ex: #FF0000', max_length=7, verbose_name='Cor Principal')),
                ('city', models.CharField(help_text='Fundamental para atrair público local. Ex: Porto Alegre', max_length=100, verbose_name='Cidade de Atuação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
