# Generated by Django 5.2.13 on 2026-05-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='generations_count',
            field=models.IntegerField(default=0, verbose_name='Posts Gerados'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Pagou Acesso Vitalício?'),
        ),
    ]
