# Generated by Django 5.2.13 on 2026-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandprofile_generations_count_brandprofile_has_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='has_paid',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='credits',
            field=models.IntegerField(default=1, verbose_name='Créditos Restantes'),
        ),
    ]
